
# SEO settings
title: "Shaurya Gupta"
title2: "" # default: ""
description: "Shaurya Gupta's Blog"
keywords: "Shaurya, Blog, Competitive, Programming, Machine, Learning, Development"
url: http://shauryab98.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: "shauryab98"
twitter_username: "shauryab98"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Shaurya Gupta"
  job      : "Sophomore at IIT Patna"
  bio      : "1+1=3 is always TRUE in my world, a balance between binary and reality."
  thumb    : /images/author.jpg
  email    : shauryab98@gmail.com
  url      : http://shauryab98.github.io
  github   : http://github.com/shauryab98
  twitter  : http://twitter.com/shauryab98
  facebook : https://www.facebook.com/shauryab98
  linkedin : http://linkedin.com/in/shauryab98

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@shauryab98"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
